---
# This is a example file for main train config
# To run a new experiment, duplicate this yaml file and rename it

# High level params
epsilon_class: Epsilon_CAE
anndata_path: /home/wergillius/Project/diffuse_differentiate/data/TFAtlas/GSE217460_210322_TFAtlas_differentiated.h5ad
sampler_class: AE_learner
lr: 0.0003
pretrain_embedder_pth: null
fix_pretrain: false
epochs: 200
max_degree: 3
search_strategy: traverse
# DataSet and Loader args
dataset_class: Root_Diffuse
split_key: split
batch_size: 64
n_neighbor: 30

# some parameter fixed for integrated_mesendo
root_cell: null
unique_token_dict: unique_token_dict
pseudotime_key: discrete_time
condition_key: TF
max_multiplexing: 1
use_batch_index: false
exp_batch_key: ""
delimiter: "++"
layers: X
check_samples: false

# epsilon net args
gene_dim: 4806
time_emb_dim: 0
n_base_perturbs: 3551
condition_emb_dim: 256
activation: Mish
hidden_size:
- 1024
- 512
- 512
- 256
- 512
- 512
- 1024
kl_weight: 0.01
