---
# This is a example file for main train config
# To run a new experiment, duplicate this yaml file and rename it

# High level params
---
# This is a example file for main train config
# To run a new experiment, duplicate this yaml file and rename it

# High level params
epsilon_class: 
anndata_path: 
sampler_class: 
lr: 0.0003
pretrain_embedder_pth: null
fix_pretrain: false
epochs: 200
max_degree: 3
search_strategy: 
# DataSet and Loader args
dataset_class: 
split_key: split
batch_size: 32
n_neighbor: 15

# some parameter fixed for integrated_mesendo
unique_token_dict: unique_token_dict
pseudotime_key: discrete_time
condition_key: TF
max_multiplexing: 1
use_batch_index: false
exp_batch_key: ""
delimiter: none
layers: X
check_samples: false
alpha: 3
repeat: 10

# epsilon net args
gene_dim:  
time_emb_dim: 0 
n_base_perturbs:  
condition_emb_dim: 256
activation: Mish
hidden_size:
- 512
- 512
- 512
- 256
- 512
- 512
- 512
kl_weight: 

# sampler args
scheduler: linear_beta_schedule
timesteps: 200
loss_type: huber
beta_start: 1e-8
beta_end: 0.001