---
# This is a example file for main train config
# To run a new experiment, duplicate this yaml file and rename it

# High level params
epsilon_class: Epsilon_Linear
anndata_path: /home/wergillius/Project/diffuse_differentiate/data/TFAtlas/GSE217460_210322_TFAtlas_differentiated.h5ad
sampler_class: Weight_l2_sampler
lr: 0.00001
pretrain_embedder_pth: null
fix_pretrain: false
use_batch_index: false
epochs: 200
epochs: 200
max_degree: 3
weight_decay : 0.00001
l2_weight: 0.000001


# DataSet and Loader args
dataset_class: Supervised_AnnDataSet
split_key: split
batch_size: 32
n_neighbor: 15

# some parameter fixed for integrated_mesendo
unique_token_dict: unique_token_dict
pseudotime_key: discrete_time
condition_key: TF
max_multiplexing: 1
use_batch_index: false
exp_batch_key: ""
delimiter: null
layers: X
check_samples: false
label_key: a3_PathSampled_X
input_rep: null

# epsilon net args
gene_dim: 4806
time_emb_dim: 0
n_base_perturbs: 3551
condition_emb_dim: 2048
activation: Mish
hidden_size:
- 2048

# sampler args
scheduler: linear_beta_schedule
timesteps: 200
loss_type: l2
beta_start: 1e-8
beta_end: 0.001